# Capstone Project Step 2: Data Wrangling


Data wrangling is the second step in the Data Science Method. This step consists of multiple components including Data Collection, Data Organization, Data Definitions, and Data Cleaning.  

EOLOS wind research station wind turbine data from was used for the project. The EOLOS wind research site is managed by the St. Anthony Falls Research Labs or University of Minnesota. The data set includes 4, 1-hour time periods of meteorological and wind turbine data. A high and low wind time period from both summer and winter are included.

Outlined below are the general steps of the Data Science Method:
    
**The Data Science Method**  


1.   Problem Identification 

2.   **Data Wrangling** 
  * Data Collection
      - Locating the data
      - Data loading
      - Data joining
   * Data Organization
      -  File structure
      -  Git & Github
  * Data Definition
      - Column names
      - Data types (numeric, categorical, timestamp, etc.)
      - Description of the columns
      - Count or percent per unique values or codes (including NA)
      - The range of values or codes  
  * Data Cleaning
      - NA or missing data
      - Duplicates
 
3.   Exploratory Data Analysis 

4.   Pre-processing and Training Data Development

5.   Modeling 

6.   Documentation

## Data Collection

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

### Load the data from the csv 4 files into 4 pandas dataframes

In [5]:
ls

DataWrangling.ipynb               figures/
data/                             models/
eolos_educational_data_set-2.pdf

In [8]:
raw_df_high_summer=pd.read_excel('data/raw/2012_08_24_highwind.xlsx',index_col='Timestamp',parse_dates=True)

In [9]:
raw_df_high_summer.head()

,Wind Speed (m/s),Real Power (kW),Wind Direction (⁰),Ambient Temperature (⁰C),Wind Speed 125.9m (m/s),Wind Speed 101.5m (m/s),Wind Speed 76.7m (m/s),Wind Speed 51.5m (m/s),Wind Speed 27.1m (m/s),Wind Speed 7.3m (m/s),...,Air Temp 7.3m (⁰C),Relative Humidity 125.9m (%),Relative Humidity 101.5m (%),Relative Humidity 76.7m (%),Relative Humidity 51.5m (%),Relative Humidity 27.1m (%),Relative Humidty 7.3m (%),Barometric Pressure (mbar),Unnamed: 38,Met Tower Variables
Timestamp,,,,,,,,,,,,,,,,,,,,,
2012-08-24 02:00:00,9.74,1497,170.8,26.9,11.69,10.43,9.64,8.310,6.436,4.069,...,26.12,48.50,49.44,49.97,51.97,52.84,0.694,970.0159,NaN,Scada Variables
2012-08-24 02:00:01,9.73,1506,171.1,26.9,11.27,10.88,9.64,7.636,6.348,4.009,...,26.12,48.27,49.40,50.22,51.90,52.91,0.694,970.0159,NaN,NaN
2012-08-24 02:00:02,9.71,1516,170.9,26.9,10.61,11.13,10.15,7.279,6.699,3.726,...,26.12,48.40,49.22,49.90,52.18,53.16,0.711,970.0325,NaN,NaN
2012-08-24 02:00:03,9.70,1544,170.6,26.9,11.42,10.63,9.88,6.685,6.233,3.475,...,26.12,48.59,49.02,49.94,52.40,53.31,0.711,969.8824,NaN,NaN
2012-08-24 02:00:04,9.71,1548,170.9,26.9,11.11,10.25,9.60,6.117,6.509,3.229,...,26.12,48.57,48.92,49.95,52.48,53.39,0.711,969.9992,NaN,NaN

In [28]:
raw_df_high_summer.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3601 entries, 2012-08-24 02:00:00 to 2012-08-24 03:00:00
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Wind Speed (m/s)              3601 non-null   float64
 1   Real Power (kW)               3601 non-null   int64
 2   Wind Direction (⁰)            3601 non-null   float64
 3   Ambient Temperature (⁰C)      3601 non-null   float64
 4   Wind Speed 125.9m (m/s)       3601 non-null   float64
 5   Wind Speed 101.5m (m/s)       3601 non-null   float64
 6   Wind Speed 76.7m (m/s)        3601 non-null   float64
 7   Wind Speed 51.5m (m/s)        3601 non-null   float64
 8   Wind Speed 27.1m (m/s)        3601 non-null   float64
 9   Wind Speed 7.3m (m/s)         3601 non-null   float64
 10  Wind Direction 125.9m (⁰)     3601 non-null   float64
 11  Wind Direction 101.5m (⁰)     3601 non-null   float64
 12  Wind Direction 76.7m (⁰)      3601 non-null   float64
 13  Wind Direction 51.5m (⁰)      3601 non-null   float64
 14  Wind Direction 27.1m (⁰)      3601 non-null   float64
 15  Wind Direction 7.3m (⁰)       3601 non-null   float64
 16  Wind Speed 127.9m (m/s)       3601 non-null   float64
 17  Wind Speed 79.1m (m/s)        3601 non-null   float64
 18  Wind Speed 29.6m (m/s)        3601 non-null   float64
 19  Wind Speed 9.9m (m/s)         3601 non-null   float64
 20  Wind Direction 127.9m (⁰)     3601 non-null   float64
 21  Wind Direction 79.1m (⁰)      3601 non-null   float64
 22  Wind Direction 29.6m (⁰)      3601 non-null   float64
 23  Wind Direction 9.9m (⁰)       3601 non-null   float64
 24  Air Temp 125.9m (⁰C)          3601 non-null   float64
 25  Air Temp 101.5m (⁰C)          3601 non-null   float64
 26  Air Temp 76.7m (⁰C)           3601 non-null   float64
 27  Air Temp 51.5m (⁰C)           3601 non-null   float64
 28  Air Temp 27.1m (⁰C)           3601 non-null   float64
 29  Air Temp 7.3m (⁰C)            3601 non-null   float64
 30  Relative Humidity 125.9m (%)  3601 non-null   float64
 31  Relative Humidity 101.5m (%)  3601 non-null   float64
 32  Relative Humidity 76.7m (%)   3601 non-null   float64
 33  Relative Humidity 51.5m (%)   3601 non-null   float64
 34  Relative Humidity 27.1m (%)   3601 non-null   float64
 35  Relative Humidty 7.3m (%)     3601 non-null   float64
 36  Barometric Pressure (mbar)    3601 non-null   float64
 37  Unnamed: 38                   0 non-null      float64
 38  Met Tower Variables           1 non-null      object
dtypes: float64(37), int64(1), object(1)
memory usage: 1.1+ MB

<font color='teal'> **Print the percent of unique values per column. Use the `df.nunique` and the size of the dataframe to calculate the percentages.**</font>

In [32]:
(raw_df_high_summer.nunique()/raw_df_high_summer.shape[0])*100

Wind Speed (m/s)                14.856984
Real Power (kW)                 43.210219
Wind Direction (⁰)               9.886143
Ambient Temperature (⁰C)         0.138850
Wind Speed 125.9m (m/s)         21.188559
Wind Speed 101.5m (m/s)         24.881977
Wind Speed 76.7m (m/s)           5.276312
Wind Speed 51.5m (m/s)          54.873646
Wind Speed 27.1m (m/s)          67.259095
Wind Speed 7.3m (m/s)           62.510414
Wind Direction 125.9m (⁰)       22.438212
Wind Direction 101.5m (⁰)       29.686198
Wind Direction 76.7m (⁰)        31.407942
Wind Direction 51.5m (⁰)        32.018884
Wind Direction 27.1m (⁰)        33.962788
Wind Direction 7.3m (⁰)         38.544849
Wind Speed 127.9m (m/s)         20.299917
Wind Speed 79.1m (m/s)          30.130519
Wind Speed 29.6m (m/s)          67.536795
Wind Speed 9.9m (m/s)           67.064704
Wind Direction 127.9m (⁰)       99.833380
Wind Direction 79.1m (⁰)        99.972230
Wind Direction 29.6m (⁰)        99.972230
Wind Direction 9.9m (⁰)         99.916690
Air Temp 125.9m (⁰C)             3.693418
Air Temp 101.5m (⁰C)             3.304638
Air Temp 76.7m (⁰C)              2.971397
Air Temp 51.5m (⁰C)              2.499306
Air Temp 27.1m (⁰C)              2.221605
Air Temp 7.3m (⁰C)               1.888364
Relative Humidity 125.9m (%)    10.441544
Relative Humidity 101.5m (%)     9.330741
Relative Humidity 76.7m (%)      8.803110
Relative Humidity 51.5m (%)      8.553180
Relative Humidity 27.1m (%)      7.414607
Relative Humidty 7.3m (%)        0.194390
Barometric Pressure (mbar)      35.851152
Unnamed: 38                      0.000000
Met Tower Variables              0.027770
dtype: float64

In [10]:
raw_df_low_summer=pd.read_excel('data/raw/2012_08_19_lowwind.xlsx',index_col='Timestamp',parse_dates=True)

In [12]:
raw_df_low_summer.head()

,Wind Speed (m/s),Real Power (kW),Wind Direction (⁰),Ambient Temperature (⁰C),Wind Speed 125.9m (m/s),Wind Speed 101.5m (m/s),Wind Speed 76.7m (m/s),Wind Speed 51.5m (m/s),Wind Speed 27.1m (m/s),Wind Speed 7.3m (m/s),...,Air Temp 7.3m (⁰C),Relative Humidity 125.9m (%),Relative Humidity 101.5m (%),Relative Humidity 76.7m (%),Relative Humidity 51.5m (%),Relative Humidity 27.1m (%),Relative Humidty 7.3m (%),Barometric Pressure (mbar),Unnamed: 38,Met Tower Variables
Timestamp,,,,,,,,,,,,,,,,,,,,,
2012-08-19 01:00:00,5.67,215,238.2,21.4,5.484,5.312,5.300,3.666,2.624,1.964,...,20.27,53.26,52.77,54.94,55.61,58.44,0.694,975.1133,NaN,Scada Variables
2012-08-19 01:00:01,5.68,217,238.4,21.4,5.381,5.290,5.485,3.746,2.746,1.987,...,20.27,53.31,52.66,54.86,55.58,58.42,0.694,975.1301,NaN,NaN
2012-08-19 01:00:02,5.68,233,238.9,21.4,5.362,5.153,5.393,3.768,2.725,2.026,...,20.27,53.27,52.62,54.72,55.65,58.41,0.694,975.0801,NaN,NaN
2012-08-19 01:00:03,5.68,212,238.9,21.4,5.487,5.159,5.393,3.860,2.740,1.991,...,20.27,53.37,52.72,54.74,55.65,58.41,0.694,975.2135,NaN,NaN
2012-08-19 01:00:04,5.68,213,239.0,21.4,5.623,5.116,5.439,3.873,2.840,2.000,...,20.27,53.36,52.69,54.77,55.68,58.44,0.694,974.9967,NaN,NaN

In [29]:
raw_df_low_summer.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3601 entries, 2012-08-19 01:00:00 to 2012-08-19 02:00:00
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Wind Speed (m/s)              3601 non-null   float64
 1   Real Power (kW)               3601 non-null   int64
 2   Wind Direction (⁰)            3601 non-null   float64
 3   Ambient Temperature (⁰C)      3601 non-null   float64
 4   Wind Speed 125.9m (m/s)       3601 non-null   float64
 5   Wind Speed 101.5m (m/s)       3601 non-null   float64
 6   Wind Speed 76.7m (m/s)        3601 non-null   float64
 7   Wind Speed 51.5m (m/s)        3601 non-null   float64
 8   Wind Speed 27.1m (m/s)        3601 non-null   float64
 9   Wind Speed 7.3m (m/s)         3601 non-null   float64
 10  Wind Direction 125.9m (⁰)     3601 non-null   float64
 11  Wind Direction 101.5m (⁰)     3601 non-null   float64
 12  Wind Direction 76.7m (⁰)      3601 non-null   float64
 13  Wind Direction 51.5m (⁰)      3601 non-null   float64
 14  Wind Direction 27.1m (⁰)      3601 non-null   float64
 15  Wind Direction 7.3m (⁰)       3601 non-null   float64
 16  Wind Speed 127.9m (m/s)       3601 non-null   float64
 17  Wind Speed 79.1m (m/s)        3601 non-null   float64
 18  Wind Speed 29.6m (m/s)        3601 non-null   float64
 19  Wind Speed 9.9m (m/s)         3601 non-null   float64
 20  Wind Direction 127.9m (⁰)     3601 non-null   float64
 21  Wind Direction 79.1m (⁰)      3601 non-null   float64
 22  Wind Direction 29.6m (⁰)      3601 non-null   float64
 23  Wind Direction 9.9m (⁰)       3601 non-null   float64
 24  Air Temp 125.9m (⁰C)          3601 non-null   float64
 25  Air Temp 101.5m (⁰C)          3601 non-null   float64
 26  Air Temp 76.7m (⁰C)           3601 non-null   float64
 27  Air Temp 51.5m (⁰C)           3601 non-null   float64
 28  Air Temp 27.1m (⁰C)           3601 non-null   float64
 29  Air Temp 7.3m (⁰C)            3601 non-null   float64
 30  Relative Humidity 125.9m (%)  3601 non-null   float64
 31  Relative Humidity 101.5m (%)  3601 non-null   float64
 32  Relative Humidity 76.7m (%)   3601 non-null   float64
 33  Relative Humidity 51.5m (%)   3601 non-null   float64
 34  Relative Humidity 27.1m (%)   3601 non-null   float64
 35  Relative Humidty 7.3m (%)     3601 non-null   float64
 36  Barometric Pressure (mbar)    3601 non-null   float64
 37  Unnamed: 38                   0 non-null      float64
 38  Met Tower Variables           1 non-null      object
dtypes: float64(37), int64(1), object(1)
memory usage: 1.1+ MB

In [33]:
(raw_df_low_summer.nunique()/raw_df_high_summer.shape[0])*100

Wind Speed (m/s)                 6.331575
Real Power (kW)                 10.413774
Wind Direction (⁰)               4.137740
Ambient Temperature (⁰C)         0.138850
Wind Speed 125.9m (m/s)         36.850875
Wind Speed 101.5m (m/s)         40.127742
Wind Speed 76.7m (m/s)           1.555124
Wind Speed 51.5m (m/s)          41.210775
Wind Speed 27.1m (m/s)          31.574563
Wind Speed 7.3m (m/s)           13.524021
Wind Direction 125.9m (⁰)        7.858928
Wind Direction 101.5m (⁰)        7.858928
Wind Direction 76.7m (⁰)         7.192447
Wind Direction 51.5m (⁰)         8.219939
Wind Direction 27.1m (⁰)        14.856984
Wind Direction 7.3m (⁰)         19.938906
Wind Speed 127.9m (m/s)         33.962788
Wind Speed 79.1m (m/s)          44.432102
Wind Speed 29.6m (m/s)          42.154957
Wind Speed 9.9m (m/s)           32.768675
Wind Direction 127.9m (⁰)       99.583449
Wind Direction 79.1m (⁰)        99.638989
Wind Direction 29.6m (⁰)        99.500139
Wind Direction 9.9m (⁰)         99.305748
Air Temp 125.9m (⁰C)             0.860872
Air Temp 101.5m (⁰C)             0.944182
Air Temp 76.7m (⁰C)              0.805332
Air Temp 51.5m (⁰C)              1.527354
Air Temp 27.1m (⁰C)              3.110247
Air Temp 7.3m (⁰C)               3.971119
Relative Humidity 125.9m (%)     7.831158
Relative Humidity 101.5m (%)     6.692585
Relative Humidity 76.7m (%)      6.081644
Relative Humidity 51.5m (%)      6.359345
Relative Humidity 27.1m (%)     10.580394
Relative Humidty 7.3m (%)        0.277701
Barometric Pressure (mbar)      32.935296
Unnamed: 38                      0.000000
Met Tower Variables              0.027770
dtype: float64

In [13]:
raw_df_low_winter=pd.read_excel('data/raw/2014_01_08_lowwind.xlsx',index_col='Timestamp',parse_dates=True)
raw_df_low_winter.head()

,Wind Speed (m/s),Real Power (kW),Wind Direction (⁰),Ambient Temperature (⁰C),Wind Speed 125.9m (m/s),Wind Speed 101.5m (m/s),Wind Speed 76.7m (m/s),Wind Speed 51.5m (m/s),Wind Speed 27.1m (m/s),Wind Speed 7.3m (m/s),...,Air Temp 7.3m (⁰C),Relative Humidity 125.9m (%),Relative Humidity 101.5m (%),Relative Humidity 76.7m (%),Relative Humidity 51.5m (%),Relative Humidity 27.1m (%),Relative Humidty 7.3m (%),Barometric Pressure (mbar),Unnamed: 38,Met Tower Variables
Timestamp,,,,,,,,,,,,,,,,,,,,,
2014-01-08 06:00:00,5.09,233,283.3,-19.2,5.866,5.523,4.977,4.513,2.888,1.949,...,-20.04,77.08,76.36,80.2,75.47,74.49,77.02,982.4351,NaN,Scada Variables
2014-01-08 06:00:01,5.09,245,283.4,-19.2,6.095,5.523,4.931,4.376,2.888,1.908,...,-20.03,77.08,76.35,80.2,75.47,74.44,77.02,982.4518,NaN,NaN
2014-01-08 06:00:02,5.09,232,283.7,-19.2,5.912,5.753,5.069,4.330,2.928,1.786,...,-20.04,77.07,76.36,80.2,75.47,74.44,77.02,982.6191,NaN,NaN
2014-01-08 06:00:03,5.09,241,283.6,-19.2,5.866,5.523,5.023,4.513,2.727,1.705,...,-20.03,77.08,76.36,80.2,75.42,74.44,77.05,982.5522,NaN,NaN
2014-01-08 06:00:04,5.11,243,283.8,-19.2,5.866,5.569,5.162,4.513,2.888,1.705,...,-20.03,77.07,76.36,80.2,75.40,74.44,77.00,982.4518,NaN,NaN

In [30]:
raw_df_low_winter.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3601 entries, 2014-01-08 06:00:00 to 2014-01-08 07:00:00
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Wind Speed (m/s)              3601 non-null   float64
 1   Real Power (kW)               3601 non-null   int64
 2   Wind Direction (⁰)            3601 non-null   float64
 3   Ambient Temperature (⁰C)      3601 non-null   float64
 4   Wind Speed 125.9m (m/s)       3601 non-null   float64
 5   Wind Speed 101.5m (m/s)       3601 non-null   float64
 6   Wind Speed 76.7m (m/s)        3601 non-null   float64
 7   Wind Speed 51.5m (m/s)        3601 non-null   float64
 8   Wind Speed 27.1m (m/s)        3601 non-null   float64
 9   Wind Speed 7.3m (m/s)         3601 non-null   float64
 10  Wind Direction 125.9m (⁰)     3601 non-null   float64
 11  Wind Direction 101.5m (⁰)     3601 non-null   float64
 12  Wind Direction 76.7m (⁰)      3601 non-null   float64
 13  Wind Direction 51.5m (⁰)      3601 non-null   float64
 14  Wind Direction 27.1m (⁰)      3601 non-null   float64
 15  Wind Direction 7.3m (⁰)       3601 non-null   float64
 16  Wind Speed 127.9m (m/s)       3601 non-null   float64
 17  Wind Speed 79.1m (m/s)        3601 non-null   float64
 18  Wind Speed 29.6m (m/s)        3601 non-null   float64
 19  Wind Speed 9.9m (m/s)         3601 non-null   float64
 20  Wind Direction 127.9m (⁰)     3601 non-null   float64
 21  Wind Direction 79.1m (⁰)      3601 non-null   float64
 22  Wind Direction 29.6m (⁰)      3601 non-null   float64
 23  Wind Direction 9.9m (⁰)       3601 non-null   float64
 24  Air Temp 125.9m (⁰C)          3601 non-null   float64
 25  Air Temp 101.5m (⁰C)          3601 non-null   float64
 26  Air Temp 76.7m (⁰C)           3601 non-null   float64
 27  Air Temp 51.5m (⁰C)           3601 non-null   float64
 28  Air Temp 27.1m (⁰C)           3601 non-null   float64
 29  Air Temp 7.3m (⁰C)            3601 non-null   float64
 30  Relative Humidity 125.9m (%)  3601 non-null   float64
 31  Relative Humidity 101.5m (%)  3601 non-null   float64
 32  Relative Humidity 76.7m (%)   3601 non-null   float64
 33  Relative Humidity 51.5m (%)   3601 non-null   float64
 34  Relative Humidity 27.1m (%)   3601 non-null   float64
 35  Relative Humidty 7.3m (%)     3601 non-null   float64
 36  Barometric Pressure (mbar)    3601 non-null   float64
 37  Unnamed: 38                   0 non-null      float64
 38  Met Tower Variables           1 non-null      object
dtypes: float64(37), int64(1), object(1)
memory usage: 1.1+ MB

In [34]:
(raw_df_low_winter.nunique()/raw_df_high_summer.shape[0])*100

Wind Speed (m/s)                 6.359345
Real Power (kW)                 10.802555
Wind Direction (⁰)               4.582061
Ambient Temperature (⁰C)         0.111080
Wind Speed 125.9m (m/s)          1.194113
Wind Speed 101.5m (m/s)          1.638434
Wind Speed 76.7m (m/s)           1.582894
Wind Speed 51.5m (m/s)           1.610664
Wind Speed 27.1m (m/s)           1.888364
Wind Speed 7.3m (m/s)            1.277423
Wind Direction 125.9m (⁰)        9.414052
Wind Direction 101.5m (⁰)       10.524854
Wind Direction 76.7m (⁰)        11.996668
Wind Direction 51.5m (⁰)        15.606776
Wind Direction 27.1m (⁰)        22.882533
Wind Direction 7.3m (⁰)         24.632047
Wind Speed 127.9m (m/s)         37.350736
Wind Speed 79.1m (m/s)          44.626493
Wind Speed 29.6m (m/s)          42.876979
Wind Speed 9.9m (m/s)           35.573452
Wind Direction 127.9m (⁰)       99.666759
Wind Direction 79.1m (⁰)        99.944460
Wind Direction 29.6m (⁰)        99.833380
Wind Direction 9.9m (⁰)         99.777839
Air Temp 125.9m (⁰C)             1.471813
Air Temp 101.5m (⁰C)             1.416273
Air Temp 76.7m (⁰C)              1.360733
Air Temp 51.5m (⁰C)              1.305193
Air Temp 27.1m (⁰C)              0.833102
Air Temp 7.3m (⁰C)               0.749792
Relative Humidity 125.9m (%)     4.693141
Relative Humidity 101.5m (%)     4.582061
Relative Humidity 76.7m (%)      2.804776
Relative Humidity 51.5m (%)      3.471258
Relative Humidity 27.1m (%)      3.332408
Relative Humidty 7.3m (%)        2.054985
Barometric Pressure (mbar)      25.853929
Unnamed: 38                      0.000000
Met Tower Variables              0.027770
dtype: float64

In [15]:
raw_df_high_winter=pd.read_excel('data/raw/2013_12_29_highwind.xlsx',index_col='Timestamp',parse_dates=True)
raw_df_high_winter.head()

,Wind Speed (m/s),Real Power (kW),Wind Direction (⁰),Ambient Temperature (⁰C),Wind Speed 125.9m (m/s),Wind Speed 101.5m (m/s),Wind Speed 76.7m (m/s),Wind Speed 51.5m (m/s),Wind Speed 27.1m (m/s),Wind Speed 7.3m (m/s),...,Air Temp 7.3m (⁰C),Relative Humidity 125.9m (%),Relative Humidity 101.5m (%),Relative Humidity 76.7m (%),Relative Humidity 51.5m (%),Relative Humidity 27.1m (%),Relative Humidty 7.3m (%),Barometric Pressure (mbar),Unnamed: 38,Met Tower Variables
Timestamp,,,,,,,,,,,,,,,,,,,,,
2013-12-29 05:00:00,13.76,2426,349.2,-4.0,14.69,11.72,12.37,11.95,14.85,14.01,...,-3.219,91.2,87.5,90.4,86.1,83.2,83.1,970.7156,NaN,Scada Variables
2013-12-29 05:00:01,13.74,2430,350.2,-4.0,14.60,12.09,12.56,12.04,14.60,15.52,...,-3.213,91.2,87.5,90.4,86.1,83.2,83.1,970.7657,NaN,NaN
2013-12-29 05:00:02,13.75,2422,351.6,-4.0,15.10,12.69,12.56,11.85,15.01,15.64,...,-3.225,91.2,87.5,90.4,86.1,83.2,83.2,970.6990,NaN,NaN
2013-12-29 05:00:03,13.76,2430,351.8,-4.0,14.87,13.74,12.93,11.90,16.25,15.93,...,-3.219,91.2,87.5,90.4,86.1,83.2,83.2,970.6823,NaN,NaN
2013-12-29 05:00:04,13.75,2407,352.0,-4.0,14.28,13.83,12.83,12.96,16.54,15.68,...,-3.219,91.2,87.5,90.3,86.1,83.2,83.2,970.6155,NaN,NaN

In [31]:
raw_df_high_winter.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3601 entries, 2013-12-29 05:00:00 to 2013-12-29 06:00:00
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Wind Speed (m/s)              3601 non-null   float64
 1   Real Power (kW)               3601 non-null   int64
 2   Wind Direction (⁰)            3601 non-null   float64
 3   Ambient Temperature (⁰C)      3601 non-null   float64
 4   Wind Speed 125.9m (m/s)       3601 non-null   float64
 5   Wind Speed 101.5m (m/s)       3601 non-null   float64
 6   Wind Speed 76.7m (m/s)        3601 non-null   float64
 7   Wind Speed 51.5m (m/s)        3601 non-null   float64
 8   Wind Speed 27.1m (m/s)        3601 non-null   float64
 9   Wind Speed 7.3m (m/s)         3601 non-null   float64
 10  Wind Direction 125.9m (⁰)     3601 non-null   float64
 11  Wind Direction 101.5m (⁰)     3601 non-null   float64
 12  Wind Direction 76.7m (⁰)      3601 non-null   float64
 13  Wind Direction 51.5m (⁰)      3601 non-null   float64
 14  Wind Direction 27.1m (⁰)      3601 non-null   float64
 15  Wind Direction 7.3m (⁰)       3601 non-null   float64
 16  Wind Speed 127.9m (m/s)       3587 non-null   float64
 17  Wind Speed 79.1m (m/s)        3601 non-null   float64
 18  Wind Speed 29.6m (m/s)        3601 non-null   float64
 19  Wind Speed 9.9m (m/s)         3601 non-null   float64
 20  Wind Direction 127.9m (⁰)     3568 non-null   float64
 21  Wind Direction 79.1m (⁰)      3568 non-null   float64
 22  Wind Direction 29.6m (⁰)      3601 non-null   float64
 23  Wind Direction 9.9m (⁰)       3601 non-null   float64
 24  Air Temp 125.9m (⁰C)          3601 non-null   float64
 25  Air Temp 101.5m (⁰C)          3601 non-null   float64
 26  Air Temp 76.7m (⁰C)           3601 non-null   float64
 27  Air Temp 51.5m (⁰C)           3601 non-null   float64
 28  Air Temp 27.1m (⁰C)           3601 non-null   float64
 29  Air Temp 7.3m (⁰C)            3601 non-null   float64
 30  Relative Humidity 125.9m (%)  3601 non-null   float64
 31  Relative Humidity 101.5m (%)  3601 non-null   float64
 32  Relative Humidity 76.7m (%)   3601 non-null   float64
 33  Relative Humidity 51.5m (%)   3601 non-null   float64
 34  Relative Humidity 27.1m (%)   3601 non-null   float64
 35  Relative Humidty 7.3m (%)     3601 non-null   float64
 36  Barometric Pressure (mbar)    3601 non-null   float64
 37  Unnamed: 38                   0 non-null      float64
 38  Met Tower Variables           1 non-null      object
dtypes: float64(37), int64(1), object(1)
memory usage: 1.1+ MB

In [35]:
(raw_df_high_winter.nunique()/raw_df_high_summer.shape[0])*100

Wind Speed (m/s)                 20.161066
Real Power (kW)                  33.129686
Wind Direction (⁰)                9.663982
Ambient Temperature (⁰C)          0.166620
Wind Speed 125.9m (m/s)           7.720078
Wind Speed 101.5m (m/s)           7.692308
Wind Speed 76.7m (m/s)            7.359067
Wind Speed 51.5m (m/s)            7.331297
Wind Speed 27.1m (m/s)            7.747848
Wind Speed 7.3m (m/s)             6.775896
Wind Direction 125.9m (⁰)        19.078034
Wind Direction 101.5m (⁰)        28.381005
Wind Direction 76.7m (⁰)         60.233269
Wind Direction 51.5m (⁰)         54.179395
Wind Direction 27.1m (⁰)         47.542349
Wind Direction 7.3m (⁰)          31.880033
Wind Speed 127.9m (m/s)          31.130242
Wind Speed 79.1m (m/s)           45.320744
Wind Speed 29.6m (m/s)           32.074424
Wind Speed 9.9m (m/s)            27.381283
Wind Direction 127.9m (⁰)        99.000278
Wind Direction 79.1m (⁰)         99.055818
Wind Direction 29.6m (⁰)         99.944460
Wind Direction 9.9m (⁰)         100.000000
Air Temp 125.9m (⁰C)              7.858928
Air Temp 101.5m (⁰C)              8.775340
Air Temp 76.7m (⁰C)               8.497640
Air Temp 51.5m (⁰C)               7.386837
Air Temp 27.1m (⁰C)               7.553457
Air Temp 7.3m (⁰C)                7.192447
Relative Humidity 125.9m (%)      1.277423
Relative Humidity 101.5m (%)      1.471813
Relative Humidity 76.7m (%)       1.610664
Relative Humidity 51.5m (%)       1.527354
Relative Humidity 27.1m (%)       1.471813
Relative Humidty 7.3m (%)         1.582894
Barometric Pressure (mbar)       34.990280
Unnamed: 38                       0.000000
Met Tower Variables               0.027770
dtype: float64

### Find index of nan values in specific rows to check if they are continuous

In [52]:
import numpy as np
index = raw_df_high_winter['Wind Speed 127.9m (m/s)'].index[raw_df_high_winter['Wind Speed 127.9m (m/s)'].apply(np.isnan)]

print(len(index))

index[0:13]

14

DatetimeIndex(['2013-12-29 05:00:55', '2013-12-29 05:01:17',
               '2013-12-29 05:25:33', '2013-12-29 05:25:37',
               '2013-12-29 05:25:56', '2013-12-29 05:27:44',
               '2013-12-29 05:28:46', '2013-12-29 05:28:47',
               '2013-12-29 05:32:37', '2013-12-29 05:49:33',
               '2013-12-29 05:50:19', '2013-12-29 05:53:10',
               '2013-12-29 05:56:30'],
              dtype='datetime64[ns]', name='Timestamp', freq=None)

In [54]:
import numpy as np
index = raw_df_high_winter['Wind Direction 127.9m (⁰)'].index[raw_df_high_winter['Wind Direction 127.9m (⁰)'].apply(np.isnan)]

print(len(index))

index[0:33]

33

DatetimeIndex(['2013-12-29 05:00:55', '2013-12-29 05:25:33',
               '2013-12-29 05:25:52', '2013-12-29 05:25:53',
               '2013-12-29 05:25:56', '2013-12-29 05:25:57',
               '2013-12-29 05:26:44', '2013-12-29 05:27:44',
               '2013-12-29 05:28:46', '2013-12-29 05:28:47',
               '2013-12-29 05:28:48', '2013-12-29 05:28:51',
               '2013-12-29 05:28:52', '2013-12-29 05:29:26',
               '2013-12-29 05:30:17', '2013-12-29 05:30:42',
               '2013-12-29 05:32:05', '2013-12-29 05:32:38',
               '2013-12-29 05:32:56', '2013-12-29 05:48:55',
               '2013-12-29 05:48:56', '2013-12-29 05:49:22',
               '2013-12-29 05:49:34', '2013-12-29 05:50:20',
               '2013-12-29 05:50:51', '2013-12-29 05:51:04',
               '2013-12-29 05:51:05', '2013-12-29 05:51:41',
               '2013-12-29 05:52:05', '2013-12-29 05:52:06',
               '2013-12-29 05:52:15', '2013-12-29 05:53:10',
               '2013-12-29 05:54:57'],
              dtype='datetime64[ns]', name='Timestamp', freq=None)

In [55]:
import numpy as np
index = raw_df_high_winter['Wind Direction 79.1m (⁰)'].index[raw_df_high_winter['Wind Direction 79.1m (⁰)'].apply(np.isnan)]

print(len(index))

index[0:33]

33

DatetimeIndex(['2013-12-29 05:00:55', '2013-12-29 05:25:33',
               '2013-12-29 05:25:52', '2013-12-29 05:25:53',
               '2013-12-29 05:25:56', '2013-12-29 05:25:57',
               '2013-12-29 05:26:44', '2013-12-29 05:27:44',
               '2013-12-29 05:28:46', '2013-12-29 05:28:47',
               '2013-12-29 05:28:48', '2013-12-29 05:28:51',
               '2013-12-29 05:28:52', '2013-12-29 05:29:26',
               '2013-12-29 05:30:17', '2013-12-29 05:30:42',
               '2013-12-29 05:32:05', '2013-12-29 05:32:38',
               '2013-12-29 05:32:56', '2013-12-29 05:48:55',
               '2013-12-29 05:48:56', '2013-12-29 05:49:22',
               '2013-12-29 05:49:34', '2013-12-29 05:50:20',
               '2013-12-29 05:50:51', '2013-12-29 05:51:04',
               '2013-12-29 05:51:05', '2013-12-29 05:51:41',
               '2013-12-29 05:52:05', '2013-12-29 05:52:06',
               '2013-12-29 05:52:15', '2013-12-29 05:53:10',
               '2013-12-29 05:54:57'],
              dtype='datetime64[ns]', name='Timestamp', freq=None)

### Interpolating to replace NAN values 
Spline method is used since there are a few continuous NAN values.

In [63]:
raw_df_high_winter['Wind Direction 79.1m (⁰)'].interpolate(method='spline',order=5,inplace=True)

In [64]:
raw_df_high_winter['Wind Direction 127.9m (⁰)'].interpolate(method='spline',order=5,inplace=True)

In [65]:
raw_df_high_winter['Wind Speed 127.9m (m/s)'].interpolate(method='spline',order=5,inplace=True)

### combine 4 dataframes to 1

In [66]:
frames = [raw_df_low_summer, raw_df_high_summer, raw_df_high_winter,raw_df_low_winter]

raw_df = pd.concat(frames)

raw_df.head()

,Wind Speed (m/s),Real Power (kW),Wind Direction (⁰),Ambient Temperature (⁰C),Wind Speed 125.9m (m/s),Wind Speed 101.5m (m/s),Wind Speed 76.7m (m/s),Wind Speed 51.5m (m/s),Wind Speed 27.1m (m/s),Wind Speed 7.3m (m/s),...,Air Temp 7.3m (⁰C),Relative Humidity 125.9m (%),Relative Humidity 101.5m (%),Relative Humidity 76.7m (%),Relative Humidity 51.5m (%),Relative Humidity 27.1m (%),Relative Humidty 7.3m (%),Barometric Pressure (mbar),Unnamed: 38,Met Tower Variables
Timestamp,,,,,,,,,,,,,,,,,,,,,
2012-08-19 01:00:00,5.67,215,238.2,21.4,5.484,5.312,5.300,3.666,2.624,1.964,...,20.27,53.26,52.77,54.94,55.61,58.44,0.694,975.1133,NaN,Scada Variables
2012-08-19 01:00:01,5.68,217,238.4,21.4,5.381,5.290,5.485,3.746,2.746,1.987,...,20.27,53.31,52.66,54.86,55.58,58.42,0.694,975.1301,NaN,NaN
2012-08-19 01:00:02,5.68,233,238.9,21.4,5.362,5.153,5.393,3.768,2.725,2.026,...,20.27,53.27,52.62,54.72,55.65,58.41,0.694,975.0801,NaN,NaN
2012-08-19 01:00:03,5.68,212,238.9,21.4,5.487,5.159,5.393,3.860,2.740,1.991,...,20.27,53.37,52.72,54.74,55.65,58.41,0.694,975.2135,NaN,NaN
2012-08-19 01:00:04,5.68,213,239.0,21.4,5.623,5.116,5.439,3.873,2.840,2.000,...,20.27,53.36,52.69,54.77,55.68,58.44,0.694,974.9967,NaN,NaN

## Data Organization

### Create subfolders in your project directory

<font color='teal'> **Create a subfolder called `data`.**</font>

In [17]:
%mkdir data

mkdir: data: File exists

<font color='teal'> **Create a folder for the data visualizations you will create in future steps called `figures`.**</font>

In [18]:
%mkdir figures

mkdir: figures: File exists

<font color='teal'> **Create a folder for the models you save, called `models`.**</font>

In [19]:
%mkdir models

mkdir: models: File exists

<font color='teal'> **Print the contents of your project folder to confirm you created the additional folders in your directory.**</font>

In [23]:
ls

DataWrangling.ipynb               figures/
data/                             models/
eolos_educational_data_set-2.pdf

## Data Definition
In this step, column names, data types, and null values will be reviewed.

### Column Names 
<font color='teal'> **Print the columns names of the entire dataframe**</font>

In [67]:
raw_df.columns

Index(['Wind Speed (m/s)', 'Real Power (kW)', 'Wind Direction (⁰)',
       'Ambient Temperature (⁰C)', 'Wind Speed 125.9m (m/s)',
       'Wind Speed 101.5m (m/s)', 'Wind Speed 76.7m (m/s)',
       'Wind Speed 51.5m (m/s)', 'Wind Speed 27.1m (m/s)',
       'Wind Speed 7.3m (m/s)', 'Wind Direction 125.9m (⁰)',
       'Wind Direction 101.5m (⁰)', 'Wind Direction 76.7m (⁰)',
       'Wind Direction 51.5m (⁰)', 'Wind Direction 27.1m (⁰)',
       'Wind Direction 7.3m (⁰)', 'Wind Speed 127.9m (m/s)',
       'Wind Speed 79.1m (m/s)', 'Wind Speed 29.6m (m/s)',
       'Wind Speed 9.9m (m/s)', 'Wind Direction 127.9m (⁰)',
       'Wind Direction 79.1m (⁰)', 'Wind Direction 29.6m (⁰)',
       'Wind Direction 9.9m (⁰)', 'Air Temp 125.9m (⁰C)',
       'Air Temp 101.5m (⁰C)', 'Air Temp 76.7m (⁰C)', 'Air Temp 51.5m (⁰C)',
       'Air Temp 27.1m (⁰C)', 'Air Temp 7.3m (⁰C)',
       'Relative Humidity 125.9m (%)', 'Relative Humidity 101.5m (%)',
       'Relative Humidity 76.7m (%)', 'Relative Humidity 51.5m (%)',
       'Relative Humidity 27.1m (%)', 'Relative Humidty 7.3m (%)',
       'Barometric Pressure (mbar)', 'Unnamed: 38', 'Met Tower Variables'],
      dtype='object')

### Data Types 
Column datatypes are reviewed if they are integer, float, categorical, or dates. This is done to make sure the data type is loaded properly in the dataframe.

In [68]:
raw_df.dtypes

Wind Speed (m/s)                float64
Real Power (kW)                   int64
Wind Direction (⁰)              float64
Ambient Temperature (⁰C)        float64
Wind Speed 125.9m (m/s)         float64
Wind Speed 101.5m (m/s)         float64
Wind Speed 76.7m (m/s)          float64
Wind Speed 51.5m (m/s)          float64
Wind Speed 27.1m (m/s)          float64
Wind Speed 7.3m (m/s)           float64
Wind Direction 125.9m (⁰)       float64
Wind Direction 101.5m (⁰)       float64
Wind Direction 76.7m (⁰)        float64
Wind Direction 51.5m (⁰)        float64
Wind Direction 27.1m (⁰)        float64
Wind Direction 7.3m (⁰)         float64
Wind Speed 127.9m (m/s)         float64
Wind Speed 79.1m (m/s)          float64
Wind Speed 29.6m (m/s)          float64
Wind Speed 9.9m (m/s)           float64
Wind Direction 127.9m (⁰)       float64
Wind Direction 79.1m (⁰)        float64
Wind Direction 29.6m (⁰)        float64
Wind Direction 9.9m (⁰)         float64
Air Temp 125.9m (⁰C)            float64
Air Temp 101.5m (⁰C)            float64
Air Temp 76.7m (⁰C)             float64
Air Temp 51.5m (⁰C)             float64
Air Temp 27.1m (⁰C)             float64
Air Temp 7.3m (⁰C)              float64
Relative Humidity 125.9m (%)    float64
Relative Humidity 101.5m (%)    float64
Relative Humidity 76.7m (%)     float64
Relative Humidity 51.5m (%)     float64
Relative Humidity 27.1m (%)     float64
Relative Humidty 7.3m (%)       float64
Barometric Pressure (mbar)      float64
Unnamed: 38                     float64
Met Tower Variables              object
dtype: object

<font color='teal'> **The `df.info()` function is used to print the count of non-null values per column. This function is used to review the column names, null value counts and data types of your data frame.**</font>

In [69]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 14404 entries, 2012-08-19 01:00:00 to 2014-01-08 07:00:00
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Wind Speed (m/s)              14404 non-null  float64
 1   Real Power (kW)               14404 non-null  int64
 2   Wind Direction (⁰)            14404 non-null  float64
 3   Ambient Temperature (⁰C)      14404 non-null  float64
 4   Wind Speed 125.9m (m/s)       14404 non-null  float64
 5   Wind Speed 101.5m (m/s)       14404 non-null  float64
 6   Wind Speed 76.7m (m/s)        14404 non-null  float64
 7   Wind Speed 51.5m (m/s)        14404 non-null  float64
 8   Wind Speed 27.1m (m/s)        14404 non-null  float64
 9   Wind Speed 7.3m (m/s)         14404 non-null  float64
 10  Wind Direction 125.9m (⁰)     14404 non-null  float64
 11  Wind Direction 101.5m (⁰)     14404 non-null  float64
 12  Wind Direction 76.7m (⁰)      14404 non-null  float64
 13  Wind Direction 51.5m (⁰)      14404 non-null  float64
 14  Wind Direction 27.1m (⁰)      14404 non-null  float64
 15  Wind Direction 7.3m (⁰)       14404 non-null  float64
 16  Wind Speed 127.9m (m/s)       14404 non-null  float64
 17  Wind Speed 79.1m (m/s)        14404 non-null  float64
 18  Wind Speed 29.6m (m/s)        14404 non-null  float64
 19  Wind Speed 9.9m (m/s)         14404 non-null  float64
 20  Wind Direction 127.9m (⁰)     14404 non-null  float64
 21  Wind Direction 79.1m (⁰)      14404 non-null  float64
 22  Wind Direction 29.6m (⁰)      14404 non-null  float64
 23  Wind Direction 9.9m (⁰)       14404 non-null  float64
 24  Air Temp 125.9m (⁰C)          14404 non-null  float64
 25  Air Temp 101.5m (⁰C)          14404 non-null  float64
 26  Air Temp 76.7m (⁰C)           14404 non-null  float64
 27  Air Temp 51.5m (⁰C)           14404 non-null  float64
 28  Air Temp 27.1m (⁰C)           14404 non-null  float64
 29  Air Temp 7.3m (⁰C)            14404 non-null  float64
 30  Relative Humidity 125.9m (%)  14404 non-null  float64
 31  Relative Humidity 101.5m (%)  14404 non-null  float64
 32  Relative Humidity 76.7m (%)   14404 non-null  float64
 33  Relative Humidity 51.5m (%)   14404 non-null  float64
 34  Relative Humidity 27.1m (%)   14404 non-null  float64
 35  Relative Humidty 7.3m (%)     14404 non-null  float64
 36  Barometric Pressure (mbar)    14404 non-null  float64
 37  Unnamed: 38                   0 non-null      float64
 38  Met Tower Variables           4 non-null      object
dtypes: float64(37), int64(1), object(1)
memory usage: 4.4+ MB

### Look for duplicate rows

In [70]:
duplicateRowsDF = raw_df[raw_df.duplicated()]
duplicateRowsDF

Empty DataFrame
Columns: [Wind Speed (m/s), Real Power (kW), Wind Direction (⁰), Ambient Temperature (⁰C), Wind Speed 125.9m (m/s), Wind Speed 101.5m (m/s), Wind Speed 76.7m (m/s), Wind Speed 51.5m (m/s), Wind Speed 27.1m (m/s), Wind Speed 7.3m (m/s), Wind Direction 125.9m (⁰), Wind Direction 101.5m (⁰), Wind Direction 76.7m (⁰), Wind Direction 51.5m (⁰), Wind Direction 27.1m (⁰), Wind Direction 7.3m (⁰), Wind Speed 127.9m (m/s), Wind Speed 79.1m (m/s), Wind Speed 29.6m (m/s), Wind Speed 9.9m (m/s), Wind Direction 127.9m (⁰), Wind Direction 79.1m (⁰), Wind Direction 29.6m (⁰), Wind Direction 9.9m (⁰), Air Temp 125.9m (⁰C), Air Temp 101.5m (⁰C), Air Temp 76.7m (⁰C), Air Temp 51.5m (⁰C), Air Temp 27.1m (⁰C), Air Temp 7.3m (⁰C), Relative Humidity 125.9m (%), Relative Humidity 101.5m (%), Relative Humidity 76.7m (%), Relative Humidity 51.5m (%), Relative Humidity 27.1m (%), Relative Humidty 7.3m (%), Barometric Pressure (mbar), Unnamed: 38, Met Tower Variables]
Index: []

[0 rows x 39 columns]

## Exporting data to a new csv file 

The last 2 columns of the data frame are deleted, since they contain informational text and not categorical or numerical data.

In [71]:
reduced_raw_df=raw_df.iloc[:,0:36]

In [73]:
reduced_raw_df.dtypes

Wind Speed (m/s)                float64
Real Power (kW)                   int64
Wind Direction (⁰)              float64
Ambient Temperature (⁰C)        float64
Wind Speed 125.9m (m/s)         float64
Wind Speed 101.5m (m/s)         float64
Wind Speed 76.7m (m/s)          float64
Wind Speed 51.5m (m/s)          float64
Wind Speed 27.1m (m/s)          float64
Wind Speed 7.3m (m/s)           float64
Wind Direction 125.9m (⁰)       float64
Wind Direction 101.5m (⁰)       float64
Wind Direction 76.7m (⁰)        float64
Wind Direction 51.5m (⁰)        float64
Wind Direction 27.1m (⁰)        float64
Wind Direction 7.3m (⁰)         float64
Wind Speed 127.9m (m/s)         float64
Wind Speed 79.1m (m/s)          float64
Wind Speed 29.6m (m/s)          float64
Wind Speed 9.9m (m/s)           float64
Wind Direction 127.9m (⁰)       float64
Wind Direction 79.1m (⁰)        float64
Wind Direction 29.6m (⁰)        float64
Wind Direction 9.9m (⁰)         float64
Air Temp 125.9m (⁰C)            float64
Air Temp 101.5m (⁰C)            float64
Air Temp 76.7m (⁰C)             float64
Air Temp 51.5m (⁰C)             float64
Air Temp 27.1m (⁰C)             float64
Air Temp 7.3m (⁰C)              float64
Relative Humidity 125.9m (%)    float64
Relative Humidity 101.5m (%)    float64
Relative Humidity 76.7m (%)     float64
Relative Humidity 51.5m (%)     float64
Relative Humidity 27.1m (%)     float64
Relative Humidty 7.3m (%)       float64
dtype: object

In [74]:
reduced_raw_df.to_csv('./data/DataWrangling_output.csv')